version: '3.8'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 myproject.asgi:application  # Daphne для запуска ASGI-приложения
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Монтируем текущую директорию внутрь контейнера
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis  # Для WebSocket можно использовать Redis

  redis:
    image: "redis:alpine"  # Redis для обработки каналов WebSocket
    volumes:
      - redis_data:/data  # Храним данные Redis

volumes:
  redis_data:  # Тома для хранения данных Redis
